C
C NUMERICAL MATHEMATICS AND COMPUTING, CHENEY/KINCAID, (c) 1985
C
C FILE: pi.f
C
C SIMPLE CODE TO ILLUSTRATE PROGRAMMING IN DOUBLE PRECISION
C
      DOUBLE PRECISION PI 
      PI = 4.0D0*DATAN(1.0D0) 
      PRINT *,PI
      STOP
      END 

