#ifndef __SGLKEY
#define __SGLKEY

#define KEY_ESCAPE          0x01
#define KEY_1               0x02
#define KEY_2               0x03
#define KEY_3               0x04
#define KEY_4               0x05
#define KEY_5               0x06
#define KEY_6               0x07
#define KEY_7               0x08
#define KEY_8               0x09
#define KEY_9               0x0A
#define KEY_0               0x0B
#define KEY_MINUS           0x0C    
#define KEY_EQUALS          0x0D
#define KEY_BACK            0x0E    
#define KEY_TAB             0x0F
#define KEY_Q               0x10
#define KEY_W               0x11
#define KEY_E               0x12
#define KEY_R               0x13
#define KEY_T               0x14
#define KEY_Y               0x15
#define KEY_U               0x16
#define KEY_I               0x17
#define KEY_O               0x18
#define KEY_P               0x19
#define KEY_LBRACKET        0x1A
#define KEY_RBRACKET        0x1B
#define KEY_RETURN          0x1C    
#define KEY_LCONTROL        0x1D
#define KEY_A               0x1E
#define KEY_S               0x1F
#define KEY_D               0x20
#define KEY_F               0x21
#define KEY_G               0x22
#define KEY_H               0x23
#define KEY_J               0x24
#define KEY_K               0x25
#define KEY_L               0x26
#define KEY_SEMICOLON       0x27
#define KEY_APOSTROPHE      0x28
#define KEY_GRAVE           0x29
#define KEY_LSHIFT          0x2A
#define KEY_BACKSLASH       0x2B
#define KEY_Z               0x2C
#define KEY_X               0x2D
#define KEY_C               0x2E
#define KEY_V               0x2F
#define KEY_B               0x30
#define KEY_N               0x31
#define KEY_M               0x32
#define KEY_COMMA           0x33
#define KEY_PERIOD          0x34
#define KEY_SLASH           0x35
#define KEY_RSHIFT          0x36
#define KEY_MULTIPLY        0x37
#define KEY_LMENU           0x38
#define KEY_SPACE           0x39
#define KEY_CAPITAL         0x3A
#define KEY_F1              0x3B
#define KEY_F2              0x3C
#define KEY_F3              0x3D
#define KEY_F4              0x3E
#define KEY_F5              0x3F
#define KEY_F6              0x40
#define KEY_F7              0x41
#define KEY_F8              0x42
#define KEY_F9              0x43
#define KEY_F10             0x44
#define KEY_NUMLOCK         0x45
#define KEY_SCROLL          0x46
#define KEY_NUMPAD7         0x47
#define KEY_NUMPAD8         0x48
#define KEY_NUMPAD9         0x49
#define KEY_SUBTRACT        0x4A
#define KEY_NUMPAD4         0x4B
#define KEY_NUMPAD5         0x4C
#define KEY_NUMPAD6         0x4D
#define KEY_ADD             0x4E
#define KEY_NUMPAD1         0x4F
#define KEY_NUMPAD2         0x50
#define KEY_NUMPAD3         0x51
#define KEY_NUMPAD0         0x52
#define KEY_DECIMAL         0x53
#define KEY_OEM_102         0x56
#define KEY_F11             0x57
#define KEY_F12             0x58
#define KEY_F13             0x64
#define KEY_F14             0x65
#define KEY_F15             0x66
#define KEY_KANA            0x70
#define KEY_ABNT_C1         0x73
#define KEY_CONVERT         0x79
#define KEY_NOCONVERT       0x7B
#define KEY_YEN             0x7D
#define KEY_ABNT_C2         0x7E
#define KEY_NUMPADEQUALS    0x8D
#define KEY_PREVTRACK       0x90
#define KEY_AT              0x91
#define KEY_COLON           0x92
#define KEY_UNDERLINE       0x93
#define KEY_KANJI           0x94
#define KEY_STOP            0x95
#define KEY_AX              0x96
#define KEY_UNLABELED       0x97
#define KEY_NEXTTRACK       0x99
#define KEY_NUMPADENTER     0x9C
#define KEY_RCONTROL        0x9D
#define KEY_MUTE            0xA0
#define KEY_CALCULATOR      0xA1
#define KEY_PLAYPAUSE       0xA2
#define KEY_MEDIASTOP       0xA4
#define KEY_VOLUMEDOWN      0xAE
#define KEY_VOLUMEUP        0xB0
#define KEY_WEBHOME         0xB2
#define KEY_NUMPADCOMMA     0xB3
#define KEY_DIVIDE          0xB5
#define KEY_SYSRQ           0xB7
#define KEY_RMENU           0xB8
#define KEY_PAUSE           0xC5
#define KEY_HOME            0xC7
#define KEY_UP              0xC8
#define KEY_PRIOR           0xC9
#define KEY_LEFT            0xCB
#define KEY_RIGHT           0xCD
#define KEY_END             0xCF
#define KEY_DOWN            0xD0
#define KEY_NEXT            0xD1
#define KEY_INSERT          0xD2
#define KEY_DELETE          0xD3
#define KEY_LWIN            0xDB
#define KEY_RWIN            0xDC
#define KEY_APPS            0xDD
#define KEY_POWER           0xDE
#define KEY_SLEEP           0xDF
#define KEY_WAKE            0xE3
#define KEY_WEBSEARCH       0xE5
#define KEY_WEBFAVORITES    0xE6
#define KEY_WEBREFRESH      0xE7
#define KEY_WEBSTOP         0xE8
#define KEY_WEBFORWARD      0xE9
#define KEY_WEBBACK         0xEA
#define KEY_MYCOMPUTER      0xEB
#define KEY_MAIL            0xEC
#define KEY_MEDIASELECT     0xED

#endif